// generated by stringer -type PlatformType main.go; DO NOT EDIT

package main

import "fmt"

const _PlatformType_name = "AndroidIOS"

var _PlatformType_index = [...]uint8{0, 7, 10}

func (i PlatformType) String() string {
	if i < 0 || i >= PlatformType(len(_PlatformType_index)-1) {
		return fmt.Sprintf("PlatformType(%d)", i)
	}
	return _PlatformType_name[_PlatformType_index[i]:_PlatformType_index[i+1]]
}
